# project directory
chdir = '{path}'

# worker processes
workers = {processes}

# threads per worker
threads = {threads}

# user to run as
user = '{user}'

# worker type
worker_class = '{worker_class}'

# bind IP and port
bind = '0.0.0.0:{port}'

# PID file path (used for stopping and restarting; do not remove)
pidfile = '{path}/gunicorn.pid'

# access log and error log paths, file name do not change 'gunicorn_acess.log', 'gunicorn_error.log'
accesslog = '{logpath}/gunicorn_acess.log'
errorlog = '{logpath}/gunicorn_error.log'

# Log level (this log level applies to the error log; the access log level cannot be configured)
# debug: Debug level;
# info: Normal level;
# warning: Warning messages level;
# error: Error level;
# critical: Critical errors;
loglevel = '{loglevel}'

# Put custom settings here
# It is best to follow the same format as above: <comment + newline + key = value>.
# PS: Gunicorn configuration files are Python\-style (i.e., ".py" files); make sure to follow Python syntax.
# For example: if a config value (such as loglevel) is a string, it must be enclosed in quotes.