[uwsgi]
# Project directory
chdir={path}

# Specify the project's application entry
wsgi-file={rfile}

# The application variable name used to start within the Python program
callable={app}

# Number of processes
processes={processes}

# Number of threads
threads={threads}

# PID file path at startup (used for stopping and restarting the service; do not remove)
pidfile={path}/uwsgi.pid

# Specify IP and port
# HTTP mode by default; can be switched to socket mode
{is_http}http=0.0.0.0:{port}
{is_socket}socket=0.0.0.0:{port}

# User and group to run uWSGI as
uid={user}
gid={user}

# Enable master process
master=true

# Set buffer size
buffer-size = 32768

# Run in background and output logs, do not change log file names 'uwsgi.log'
daemonize = {logpath}/uwsgi.log

# Write custom settings here\,
# If you do not want to use wsgi-file as the project's startup method, comment it out, but do not delete it; the same applies to the communication method (http, socket)\;
# It is best to follow the same format as above: <comment + newline + key = value> for readability and future reference
